./main "testcases/assign"
./main "testcases/decl"
./main "testcases/declchannel"
./main "testcases/goblock"
./main "testcases/print"
./main "testcases/recv"
./main "testcases/statements"
./main "testcases/transmit"
./main "testcases/while"
./main "testcases/ifelse"
./main "testcases/return"
./main "testcases/funccall"
# ./main "testcases/proc" # fails
./main "testcases/exp"
